import React from "react"
 export default function AboutFest() {
  return  (
        <div className='aboutFest'>
            <h2 className="FestHeader">About Miracle Fest</h2>
            <p className='about-fest-content'>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Voluptatum vel quam molestias incidunt tempora aut pariatur eaque facere maiores! Deleniti iusto ullam et tenetur suscipit voluptates odit neque veniam minima.
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Culpa velit expedita labore voluptatem pariatur at iure, officiis totam ullam natus quas saepe maiores quos illo autem. Repellat aut veniam perspiciatis.
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Culpa repudiandae voluptate aperiam maxime? Eaque inventore quos ut illum tempore! Totam accusantium et recusandae placeat. Cum assumenda id ad dolor dolores?
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi aut nostrum aliquam eveniet sint ut quod dolore quos ab quisquam doloremque debitis, tempora aspernatur omnis maiores vitae quia harum est?
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Enim neque totam eum ducimus. Placeat error unde excepturi nulla voluptatum commodi recusandae aspernatur, alias assumenda voluptatibus quibusdam, neque ipsa suscipit numquam.
                Lorem ipsum, dolor sit amet consectetur adipisicing elit. Repellendus sit neque, eius cumque nemo nisi optio maxime assumenda aliquid voluptate. Omnis quasi facilis quis, harum nisi esse porro dolore vero.
                Lorem ipsum dolor sit, amet consectetur adipisicing elit. Cupiditate non voluptas blanditiis, consequuntur optio ipsum repudiandae, harum exercitationem reiciendis at voluptates corporis sint quam animi quae labore eaque voluptatibus eligendi?
                Doloribus amet voluptatum accusamus, soluta a at eligendi natus quos repellendus, magni, tempora qui. Sint exercitationem dolor rem sed officiis quo! Amet, eligendi eaque esse nobis blanditiis saepe voluptatibus eum.
                Quis perferendis corporis atque ipsam accusamus dolorem officiis suscipit! Repudiandae totam nesciunt impedit, ipsum doloribus delectus perferendis expedita veritatis? Deleniti suscipit dolorem minus illum tempore corrupti dolor tenetur, sapiente iure?
                Perferendis neque totam ducimus, autem officia debitis at libero, a veritatis obcaecati dolores odio aspernatur officiis fugiat cumque quod sed quibusdam nemo nulla odit modi laboriosam inventore nihil doloremque! Et.
                Saepe officia quisquam magnam quidem quod. Explicabo incidunt cum harum laudantium nemo. Iure, inventore eveniet. Ad minima laboriosam natus veniam velit aliquam dicta cum magni, nostrum quasi delectus, similique dolor!
                Doloremque excepturi dolorem eius sed doloribus tenetur officiis aliquam ducimus quaerat iusto dolor nisi quidem, ratione odit? Obcaecati dolore nesciunt eligendi, nostrum, unde eveniet veniam, suscipit reiciendis impedit excepturi quas?
                Dolores cum, possimus cupiditate excepturi soluta, obcaecati magnam blanditiis quisquam atque voluptates, asperiores quos aspernatur dolore. Doloribus voluptates dolore iste tempore aliquid veniam repellendus recusandae ad a! Sint, ipsum laudantium?
                Excepturi consequatur incidunt, neque deserunt laborum ipsam modi adipisci aliquid cumque, iusto aut voluptas? Nostrum dolor inventore non accusantium necessitatibus suscipit, deleniti tempore natus doloremque, vero sequi atque enim doloribus.
                Est odio a, magni voluptatibus blanditiis optio cumque vitae dicta soluta exercitationem assumenda labore recusandae quisquam, dolor, impedit at nemo magnam sequi animi! Accusantium ut incidunt rem tenetur obcaecati beatae.
                Harum exercitationem magnam, modi quaerat aliquid necessitatibus et totam excepturi incidunt sed facere deserunt veritatis dolore magni neque unde eum quia molestias accusantium nostrum autem voluptates consectetur porro. Ducimus, amet?
                Doloribus dignissimos quasi quas cupiditate earum, id esse necessitatibus. Est distinctio voluptas cum, maxime eaque quia ex! Excepturi, eaque suscipit aperiam possimus eligendi veritatis optio assumenda quaerat numquam, doloribus asperiores.
                Provident facilis pariatur explicabo dolore at nisi qui repellendus recusandae libero. Impedit sapiente ex saepe provident eius deserunt corporis facilis fuga, illum maiores porro, praesentium laboriosam corrupti. Temporibus, in. Dolorem.
                Nemo tempora itaque eveniet quaerat assumenda est eum exercitationem doloribus aut a error suscipit quis libero distinctio animi cumque minima ducimus dignissimos, doloremque odit asperiores inventore. Ipsam nam nisi maiores!
                Ducimus et obcaecati tempore odio quo blanditiis voluptate explicabo? Adipisci incidunt numquam reprehenderit vel error perferendis, at aliquid architecto sit. Repudiandae maiores minus voluptatum sit dolores sapiente ducimus, aliquam ipsum.
                Ea recusandae eos ullam ab harum explicabo vel assumenda sint perspiciatis earum laudantium quis unde iste enim, nisi doloribus libero! Ex quod voluptate tempore commodi unde et expedita deleniti at!
                Sapiente temporibus, molestiae nulla itaque architecto quod qui, accusantium inventore dicta fuga nihil unde nisi aperiam laborum numquam aut ducimus recusandae in totam tempore? Suscipit totam nam accusantium officia amet.
                Aliquid, at molestias quos reiciendis quis corporis, magnam voluptas vero enim mollitia consequatur quas cum consectetur minima totam placeat sit. Fugiat nam ducimus reiciendis, perspiciatis repellendus eum placeat asperiores dolorum?
                Facere, totam labore autem alias, eaque eveniet dignissimos ipsam ipsum consequuntur maxime doloremque rerum tempore accusantium sapiente inventore quisquam. Beatae cum placeat eius, qui soluta modi at illo officia et?
                Veniam illum ipsum accusamus. Dolorem fugiat molestiae consectetur asperiores consequatur voluptatum voluptate eaque, sequi omnis itaque cum repellat ratione eveniet alias laudantium animi accusamus laborum labore sunt esse minus repudiandae?
                Beatae pariatur asperiores quisquam excepturi ducimus, sapiente at nisi numquam officiis veritatis eius. Laborum officia quidem earum illum tenetur minus vero voluptatum, nulla eos nobis accusamus ducimus sit esse facere?
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum pariatur dolore libero commodi, obcaecati eum. Qui provident minima repellendus esse sit nisi, nobis, tempore omnis assumenda beatae at iure repudiandae!
                Ad, atque nobis asperiores pariatur dolore, sint iste esse beatae facilis aperiam error ipsa qui hic dolor a repudiandae, iure cumque tenetur! Exercitationem sed deserunt aliquam sint sunt consectetur quo!
                Debitis repudiandae tempora voluptatibus assumenda consequuntur iure quia maiores quibusdam temporibus neque esse autem, soluta illum exercitationem ut enim officia, harum architecto optio. Voluptate assumenda in reiciendis eum natus aperiam?
                Dolore tempora accusantium esse reprehenderit tempore. Odit nobis nulla ex vel porro. Fugit temporibus accusamus maiores velit dolores tempora fugiat unde vitae placeat ducimus accusantium, suscipit, iure sed provident ratione?
                Vero eligendi iusto molestiae saepe eos modi magni pariatur perspiciatis error ad reiciendis odio, optio distinctio debitis ratione corrupti laudantium, voluptatum veniam tempore blanditiis! Culpa ab repudiandae atque vitae excepturi.
                Quod explicabo rerum libero in dicta? Libero numquam, rem aperiam esse maiores culpa sed quis delectus, neque, autem labore aut ex officiis itaque qui ducimus minus. Accusantium excepturi nam modi.
                Incidunt debitis similique ipsa, consequatur eaque perspiciatis pariatur repellendus aliquid nulla iure quae assumenda voluptates totam? Numquam modi culpa, non illum obcaecati eum, a suscipit labore fuga deserunt, excepturi commodi?
                Placeat animi modi obcaecati delectus veniam repudiandae natus dolore omnis! Voluptas omnis nobis aliquid pariatur quibusdam delectus placeat reiciendis ducimus itaque? Ratione ullam facilis iusto accusantium quisquam similique, aut cupiditate.
                Numquam eveniet, distinctio dolorum magni ut fuga perspiciatis obcaecati. Ut, unde dignissimos maxime eos, consequatur totam praesentium temporibus consectetur fugit doloremque quas doloribus earum nisi alias necessitatibus aspernatur quasi iure!
                Voluptatem accusantium asperiores totam explicabo eius, nostrum maiores obcaecati natus! Magnam vitae, mollitia placeat velit molestias culpa optio sint accusantium harum voluptates. Harum, aliquam a! Sed eos magnam quibusdam iste.
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Error repellat aspernatur nisi nulla atque, vitae doloribus fugit sequi quod ipsum ipsa dignissimos eum vero tempore adipisci aut? Fugit, dolor sint.
                Repudiandae accusantium, fugit voluptates earum hic nemo, excepturi fugiat alias ratione accusamus error, eum mollitia. Explicabo quae dolorum eum quod, atque error, fugit harum iusto laboriosam dolorem, incidunt aut minus?
                Earum nihil totam deleniti doloribus error iure doloremque? Veniam veritatis ex in, consequuntur sint illo delectus. Quae laboriosam illum provident optio, sed culpa accusantium eum deleniti doloremque aut? Praesentium, id.
                Obcaecati laudantium maiores mollitia necessitatibus dolor numquam aperiam eaque quae ex quis quas quibusdam ipsam fugit dolorem amet quos soluta facilis enim placeat, dicta odio magnam omnis! Nihil, quidem repellat.
                Fugiat, quisquam? Illum cumque adipisci et a quod iusto hic rem eaque odio debitis provident delectus porro esse, beatae non ex, odit sed ea nemo sapiente veniam eveniet similique. Vitae.
            </p>
        </div>
    )
}
